# Generated by Django 5.1.6 on 2025-02-18 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postclapsmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_claps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postcommentclapsmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_claps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postcommentsmodel',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app_posts.postcommentsmodel'),
        ),
        migrations.AddField(
            model_name='postcommentsmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postcommentclapsmodel',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claps', to='app_posts.postcommentsmodel'),
        ),
        migrations.AddField(
            model_name='postsmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postcommentsmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_posts.postsmodel'),
        ),
        migrations.AddField(
            model_name='postclapsmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claps', to='app_posts.postsmodel'),
        ),
        migrations.AddField(
            model_name='postsmodel',
            name='topics',
            field=models.ManyToManyField(related_name='posts', to='app_posts.posttopicmodel'),
        ),
    ]
