# Generated by Django 5.1.6 on 2025-02-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0002_postsmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsmodel',
            name='slug',
            field=models.TextField(null=True, unique=True),
        ),
    ]
