# Generated by Django 5.1.6 on 2025-02-19 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcommentsmodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app_posts.postcommentsmodel'),
        ),
    ]
