# Generated by Django 5.1.6 on 2025-02-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0003_postsmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
