# Generated by Django 5.1.6 on 2025-02-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0005_posttopicmodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttopicmodel',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
