# Generated by Django 5.1.6 on 2025-02-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0006_posttopicmodel_slug'),
        ('app_topics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postclapsmodel',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postclapsmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postcommentclapsmodel',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='postcommentclapsmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postcommentsmodel',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='postcommentsmodel',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postcommentsmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='posttopicmodel',
            name='author',
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='topics',
            field=models.ManyToManyField(related_name='posts', to='app_topics.posttopicmodel'),
        ),
        migrations.DeleteModel(
            name='FollowTopicModel',
        ),
        migrations.DeleteModel(
            name='PostClapsModel',
        ),
        migrations.DeleteModel(
            name='PostCommentClapsModel',
        ),
        migrations.DeleteModel(
            name='PostCommentsModel',
        ),
        migrations.DeleteModel(
            name='PostTopicModel',
        ),
    ]
