# Generated by Django 5.1.6 on 2025-02-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcodesmodel',
            name='minutes_to_expire',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
