# Generated by Django 5.1.6 on 2025-02-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_confirmationcodesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcodesmodel',
            name='code',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='confirmationcodesmodel',
            name='minutes_to_expire',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
