# Generated by Django 5.1.6 on 2025-02-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_alter_confirmationcodesmodel_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcodesmodel',
            name='code',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
