# Generated by Django 5.1.6 on 2025-02-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_alter_confirmationcodesmodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcodesmodel',
            name='minutes_to_expire',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
