# Generated by Django 5.1.6 on 2025-02-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_alter_confirmationcodesmodel_minutes_to_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcodesmodel',
            name='minutes_to_expire',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
